# Generated by Django 6.0.2 on 2026-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_posting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
